# Lab 1 and 2 (NumPy, Pandas - 10 points)

In [96]:
#import here all needed libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot
import seaborn as sbn

-----

## NumPy

#### 1. Create a null vector of size 10 (★☆☆)

In [97]:
a = np.linspace(0,0,10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2. Create a vector with values ranging from 10 to 49 (★☆☆)

In [98]:
a2 = np.arange(10,50,1)
print(a2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [99]:
m = np.arange(9).reshape(3,3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 4. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: np.random.random()`

In [100]:
a = np.random.random((10,10))
print(a.min)
print(a.max)
print(a)

<built-in method min of numpy.ndarray object at 0x000001B0BF27F990>
<built-in method max of numpy.ndarray object at 0x000001B0BF27F990>
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.

#### 5. Create the given matrix: (★☆☆)
```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
 ```

In [165]:
m = np.zeros((5,5))
print(m)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Run the code below to get the matrix for the tasks from 6 to 10:

In [102]:
a = np.random.seed(42)

#### 6. Print the first and the last row with one slice operation  (★☆☆)

In [114]:
m= np.arange(9).reshape(3,3)
m = np.delete(m,1,axis=0)
print(m)


[[0 1 2]
 [6 7 8]]


#### 7. Print all elements less than 10  (★☆☆)

In [104]:
# your solution


#### 8. Print each even row  (★☆☆)

In [105]:
# your solution


#### 9. Print each odd column  (★☆☆)

In [106]:
# your solution


#### 10. Create the copy of this matrix and name it M2  (★☆☆)

In [107]:
# your solution


#### 11. Find the mean of each row of M1 (★★☆)

In [108]:
# your solutionSSSS


#### 12. Create the following matrix: (★☆☆)
```
[[5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5]]
```

In [109]:
a = np.full((3,5),5)
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


#### 13. Add this two arrays and calculate the square of each element: (★★☆)

```
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]
```

In [170]:
# your solution
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
c= arrayOne + arrayTwo
c = c*c
print(c)


[[ 400 1521 1089]
 [ 625  625  784]]


### Hard level Bonus

#### 14. Create the following matrix and get the highlighted parts with indexing and slicing: (★★★)


In [129]:
m= np.arange(11,36).reshape(5,5)
print(m[:,1])



[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[12 17 22 27 32]


In [130]:
m= np.arange(11,36).reshape(5,5)
print(m[::2,::2])


[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [139]:
m= np.arange(11,36).reshape(5,5)
print(m[1:4,0])

[16 21 26]


In [140]:
m= np.arange(11,36).reshape(5,5)
print(m[0,1:4])

[12 13 14]


#### 15. Create the following matrix and get the highlighted parts with indexing and slicing: (★★★)



In [151]:
m= np.arange(0,5).reshape(6,6)


ValueError: cannot reshape array of size 5 into shape (6,6)

-----

## Pandas (5 points)

In [113]:
# import the datafile "video_games_sales.csv"
# https://www.kaggle.com/datasets/hamedetezadi/video-games-sales-dataset

df  = pd.read_csv('video_games_sales.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'video_games_sales.csv'

This dataset contains a list of video games with sales greater than 100,000 copies. (It was generated by a scrape of vgchartz.com)
.

Fields include

- Rank - Ranking of overall sales
- Name - The games name
- Platform - Platform of the games release (i.e. PC,PS4, etc.)
- Year - Year of the game's release
- Genre - Genre of the game
- Publisher - Publisher of the game
- NA_Sales - Sales in North America (in millions)
- EU_Sales - Sales in Europe (in millions)
- JP_Sales - Sales in Japan (in millions)
- Other_Sales - Sales in the rest of the world (in millions)
- Global_Sales - Total worldwide sales.

**1. Show the first 5 items of dataframe (★☆☆)**

In [ ]:
# show the first 5 items of dataframe


**2. Print the column names  (★☆☆)**

In [ ]:
# print the column names



**3. Show the first 5 items of dataframe sorted by year of release (newest first) (★☆☆)**

In [ ]:
# show the first 5 items of dataframe sorted by year of release (newest first)



**4. What is the mean of "Years of Release" feature? Show  (★☆☆)**

In [ ]:
# What is the mean of "Years of Release" feature?  Show



**5. Show first 5 games was published by "Sega"? (★☆☆)**

In [ ]:
# Show first 5 games was published by "Sega"?



**6. Show the dataframe with games that was Published by "Ubisoft" and 'Sports' genre  (★☆☆)**

In [ ]:
# Show the dataframe with games that was Published by "Ubisoft" and 'Sports' genre



**7. What is the name of game which has the maximum sales in EU? Show (★☆☆)**

In [ ]:
# What is the name of game which has the maximum sales in EU? Show



**8. Calculate the difference between the maximum and minimum of global sales? (★★☆)**

In [ ]:
# Calculate the difference between the maximum and minimum of global sales?



**9. Show the histogram of Critic Score  (★★☆)**

In [ ]:
# Show the histogram of Critic Score



**10. Show the histogram of Critic Score of games released in 2010 (★★☆)**

In [ ]:
# Show the histogram of Critic Score of games released in 2010

