# Lab 1 and 2 (NumPy, Pandas - 10 points)

In [58]:
#import here all needed libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot
#import seaborn as sbn

-----

## NumPy

#### 1. Create a null vector of size 10 (★☆☆)

In [10]:
# your solution
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
# your solution
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 3. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
# your solution

np.array(range(9)).reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 4. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: np.random.random()`

In [36]:
# your solution

a = np.random.randint(60, size=(10,10))

print(a)

print('min =', np.amin(a))
print('max =', np.amax(a))

[[11 41  0 15 59 10 55 18 41 54]
 [18 23  8 22  9  1 24 39 27 49]
 [18 11 54 53 19 39  9  3 15 29]
 [10 34 31  6 33 13 54 53 48 33]
 [21 18 34 19 11 48 34 37 51 53]
 [52 40 27  3  4 57 35 27 28 21]
 [44 36 17 43 13  4  1 13  7 30]
 [17 52 40 46 49 33 59 35 49 28]
 [54 28 42 18 39 50 20 29 10 22]
 [41 48 37 43 26 13 38 30 41 29]]
min = 0
max = 59


#### 5. Create the given matrix: (★☆☆)
```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
 ```

In [ ]:
# your solution
diag = np.arange(1,5)

np.diag(diag, k=-1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Run the code below to get the matrix for the tasks from 6 to 10:

In [18]:
np.random.seed(42)

a = np.random.randint(60, size=(10,10))
print(a)


[[38 51 28 14 42  7 20 38 57 18]
 [22 10 10 23 52 35 39 23  2 21]
 [52  1 23 43 29 37  1 59 20 32]
 [11 57 21 43 24 48 26 58 41 27]
 [59 15 14 46 50 43 54 51 56  2]
 [36 50  6 20  8 38 17  3 24 59]
 [13 49 57  8 25 52  1 19 27 46]
 [59  6 43  7 46 34 13 16 35 49]
 [39  3  1  5 53 41  3 53 28 17]
 [25 43 33  9 35 13 30 47 14  7]]


#### 6. Print the first and the last row with one slice operation  (★☆☆)

In [17]:
# your solution

np.random.seed(42)

a = np.random.randint(60, size=(10,10))

print(a[0])
print(a[-1])

[38 51 28 14 42  7 20 38 57 18]
[25 43 33  9 35 13 30 47 14  7]


#### 7. Print all elements less than 10  (★☆☆)

In [38]:
# your solution
np.random.seed(42)

a = np.random.randint(60, size=(10,10))

print(a)

[[38 51 28 14 42  7 20 38 57 18]
 [22 10 10 23 52 35 39 23  2 21]
 [52  1 23 43 29 37  1 59 20 32]
 [11 57 21 43 24 48 26 58 41 27]
 [59 15 14 46 50 43 54 51 56  2]
 [36 50  6 20  8 38 17  3 24 59]
 [13 49 57  8 25 52  1 19 27 46]
 [59  6 43  7 46 34 13 16 35 49]
 [39  3  1  5 53 41  3 53 28 17]
 [25 43 33  9 35 13 30 47 14  7]]


#### 8. Print each even row  (★☆☆)

In [39]:
# your solution
np.random.seed(42)

a = np.random.randint(60, size=(10,10))

print(a[1::2])

[[22 10 10 23 52 35 39 23  2 21]
 [11 57 21 43 24 48 26 58 41 27]
 [36 50  6 20  8 38 17  3 24 59]
 [59  6 43  7 46 34 13 16 35 49]
 [25 43 33  9 35 13 30 47 14  7]]


#### 9. Print each odd column  (★☆☆)

In [40]:
# your solution
np.random.seed(42)

a = np.random.randint(60, size=(10,10))

b = a.transpose()[::2]

print(b.transpose())

[[38 28 42 20 57]
 [22 10 52 39  2]
 [52 23 29  1 20]
 [11 21 24 26 41]
 [59 14 50 54 56]
 [36  6  8 17 24]
 [13 57 25  1 27]
 [59 43 46 13 35]
 [39  1 53  3 28]
 [25 33 35 30 14]]


#### 10. Create the copy of this matrix and name it M2  (★☆☆)

In [41]:
# your solution
np.random.seed(42)

a = np.random.randint(60, size=(10,10))

M2 = a.copy()

print(M2)

[[38 51 28 14 42  7 20 38 57 18]
 [22 10 10 23 52 35 39 23  2 21]
 [52  1 23 43 29 37  1 59 20 32]
 [11 57 21 43 24 48 26 58 41 27]
 [59 15 14 46 50 43 54 51 56  2]
 [36 50  6 20  8 38 17  3 24 59]
 [13 49 57  8 25 52  1 19 27 46]
 [59  6 43  7 46 34 13 16 35 49]
 [39  3  1  5 53 41  3 53 28 17]
 [25 43 33  9 35 13 30 47 14  7]]


#### 11. Find the mean of each row of M1 (★★☆)

In [49]:
# your solution
np.random.seed(42)

a = np.random.randint(60, size=(10,10))

print(np.mean(a, axis=1))


[31.3 23.7 29.7 35.6 39.  26.1 29.7 30.8 24.3 25.6]


#### 12. Create the following matrix: (★☆☆)
```
[[5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5]]
```

In [53]:
# your solution
a = np.full((3,5), 5)

print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


#### 13. Add this two arrays and calculate the square of each element: (★★☆)

```
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]
```

In [56]:
# your solution
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

b = np.add(arrayOne, arrayTwo)

print(np.power(b, 2))

[[ 400 1521 1089]
 [ 625  625  784]]


### Hard level Bonus

#### 14. Create the following matrix and get the highlighted parts with indexing and slicing: (★★★)
![image.png](attachment:image.png)

In [ ]:
# your solution



matrix([[20, 22, 24],
        [40, 42, 44]])

matrix([[ 2],
        [12],
        [22],
        [32],
        [42],
        [52]])

matrix([[3, 4]])

matrix([[44, 45],
        [54, 55]])

#### 15. Create the following matrix and get the highlighted parts with indexing and slicing: (★★★)
![image.png](attachment:image.png)

In [ ]:
# your solution


matrix([[ 2, 22, 52]])

matrix([[30, 32, 35],
        [40, 42, 45],
        [50, 52, 55]])

matrix([[ 1, 12, 23, 34, 45]])

-----

## Pandas (5 points)

In [60]:
# import the datafile "video_games_sales.csv"
# https://www.kaggle.com/datasets/hamedetezadi/video-games-sales-dataset

df  = pd.read_csv('./video_games_sales.csv')
print(df)

                                Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii           2006.0        Sports   
1                  Super Mario Bros.      NES           1985.0      Platform   
2                     Mario Kart Wii      Wii           2008.0        Racing   
3                  Wii Sports Resort      Wii           2009.0        Sports   
4           Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3           2016.0        Action   
16715               LMA Manager 2007     X360           2006.0        Sports   
16716        Haitaka no Psychedelica      PSV           2016.0     Adventure   
16717               Spirits & Spells      GBA           2003.0      Platform   
16718            Winning Post 8 2016      PSV           2016.0    Simulation   

          Publisher  NA_Sales  EU_Sales

This dataset contains a list of video games with sales greater than 100,000 copies. (It was generated by a scrape of vgchartz.com)
.

Fields include

- Rank - Ranking of overall sales
- Name - The games name
- Platform - Platform of the games release (i.e. PC,PS4, etc.)
- Year - Year of the game's release
- Genre - Genre of the game
- Publisher - Publisher of the game
- NA_Sales - Sales in North America (in millions)
- EU_Sales - Sales in Europe (in millions)
- JP_Sales - Sales in Japan (in millions)
- Other_Sales - Sales in the rest of the world (in millions)
- Global_Sales - Total worldwide sales.

**1. Show the first 5 items of dataframe (★☆☆)**

In [ ]:
# show the first 5 items of dataframe


**2. Print the column names  (★☆☆)**

In [ ]:
# print the column names



**3. Show the first 5 items of dataframe sorted by year of release (newest first) (★☆☆)**

In [ ]:
# show the first 5 items of dataframe sorted by year of release (newest first)



**4. What is the mean of "Years of Release" feature? Show  (★☆☆)**

In [ ]:
# What is the mean of "Years of Release" feature?  Show



**5. Show first 5 games was published by "Sega"? (★☆☆)**

In [ ]:
# Show first 5 games was published by "Sega"?



**6. Show the dataframe with games that was Published by "Ubisoft" and 'Sports' genre  (★☆☆)**

In [ ]:
# Show the dataframe with games that was Published by "Ubisoft" and 'Sports' genre



**7. What is the name of game which has the maximum sales in EU? Show (★☆☆)**

In [ ]:
# What is the name of game which has the maximum sales in EU? Show



**8. Calculate the difference between the maximum and minimum of global sales? (★★☆)**

In [ ]:
# Calculate the difference between the maximum and minimum of global sales?



**9. Show the histogram of Critic Score  (★★☆)**

In [ ]:
# Show the histogram of Critic Score



**10. Show the histogram of Critic Score of games released in 2010 (★★☆)**

In [ ]:
# Show the histogram of Critic Score of games released in 2010

